name: Handle Windows Release
on:
  release:
    types: [created]
jobs:
  generate:
    name: Create release-artifacts
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
      - uses: actions/checkout@v2
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run dist-win
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'dist/elastos-light-wallet*'
